development:
  adapter: postgresql
  database: foreman_development
  username: postgres
  password: def!ne_p0stgre
  host: localhost
  encoding: UTF8

test:
  adapter: postgresql
  database: foreman_test
  username: postgres
  password: def!ne_p0stgre
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: foreman_production
  username: postgres
  password:
  host: localhost
  encoding: UTF8